import Head from 'next/head'
import {
    Intro,
    About,
    Featured,
    Projects,
    Contact,
    Layout,
    Experience,
} from '@components'

export default function Home() {
    return (
        <>
            {/**  fragment above, for majority of dev. was a DIV  **/}
            <Head>
                <title>MikeJayne.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Layout>
                <Intro />
                <About />
                <Experience />
                <Featured />
                <Projects />
                <Contact />
            </Layout>
        </>
    )
}
